
default:
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .cargo
      - firmware/target
      - host/target

stages:
  - stage1
  - stage2

.host-deps:
  before_script:
    - apt-get update
    - apt-get install -y libudev-dev

fmt:
  stage: stage1
  image: rust:latest
  script:
    - (cd firmware && cargo fmt --check)
    - (cd host && cargo fmt --check)

check-fw:
  stage: stage1
  image: rust:latest
  script:
    - cd firmware && cargo check

check-host:
  stage: stage1
  image: rust:latest
  extends: .host-deps
  script:
    - cd host && cargo check

build-book:
  stage: stage1
  image: rust:latest
  before_script:
    - cargo install mdbook
  script:
    - cd exercise-book && mdbook build
  artifacts:
    paths:
      - exercise-book/book/

build-fw:
  stage: stage2
  image: rust:latest
  before_script:
    - cargo install flip-link
  script:
    - cd firmware && cargo build

build-host:
  stage: stage2
  image: rust:latest
  extends: .host-deps
  script:
    - cd host && cargo build

clippy-fw:
  stage: stage1
  image: rust:latest
  script:
    - cd firmware && cargo clippy

clippy-host:
  stage: stage1
  image: rust:latest
  extends: .host-deps
  script:
    - cd host && cargo clippy
