variables:
  CARGO_HOME: ${CI_PROJECT_DIR}/.cargo

default:
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .cargo
      - target

stages:
  - stage1
  - stage2

fmt:
  stage: stage1
  image: rust:latest
  script:
    - cd microbit-apps && cargo fmt --check
    - cd ../microbit-exercises && cargo fmt --check

check-apps:
  stage: stage1
  image: rust:latest
  script:
    - cd microbit-apps && cargo check

check-exercises:
  stage: stage1
  image: rust:latest
  script:
    - cd microbit-exercises && cargo check

build-book:
  stage: stage1
  image: rust:latest
  before_script:
    - cargo install mdbook
  script:
    - cd exercise-book && mdbook build
  artifacts:
    paths:
      - exercise-book/book/

build-apps:
  stage: stage2
  image: rust:latest
  script:
    - cd microbit-apps && cargo build

build-exercises:
  stage: stage2
  image: rust:latest
  script:
    - cd microbit-exercises && cargo build
